controller_name: xtreet_bb
controller_type: directional_trading
manual_kill_switch: null
candles_config: []
trading_pair: NULS-USDT
connector_name: binance_perpetual
interval: 1m
max_executors_per_side: 1
cooldown_time: 0
leverage: 20
position_mode: HEDGE
time_limit: 86400
dca_spreads:
- -1.0e-05
- 0.010752688172043048
dca_amounts_pct:
- 1
- 5.017564097872069
bb_length: 200
bb_std: 1.4
stop_loss: 0.010752688172043048
take_profit: null
trailing_stop:
  activation_price: 0.015515865742794607
  trailing_delta: 0.0031031731485589215
total_amount_quote: 300
candles_trading_pair: NULS-USDT
candles_connector: binance_perpetual
id: xtreet_bb_binance_perpetual_1m_NULS-USDT_bb200_1.4_sl1.1_ts1.6-0.3bep0.009
