controller_name: xtreet_bb
controller_type: directional_trading
manual_kill_switch: null
candles_config: []
trading_pair: NULS-USDT
connector_name: binance_perpetual
interval: 1m
max_executors_per_side: 1
cooldown_time: 0
leverage: 20
position_mode: HEDGE
time_limit: 86400
dca_spreads:
- -1.0e-05
- 0.053129195700233826
dca_amounts_pct:
- 1
- 12.904062351199578
bb_length: 100
bb_std: 2.5
stop_loss: 0.030111704711024822
take_profit: null
trailing_stop:
  activation_price: 0.016503356488259145
  trailing_delta: 0.003300671297651829
total_amount_quote: 300
candles_trading_pair: NULS-USDT
candles_connector: binance_perpetual
id: xtreet_bb_binance_perpetual_1m_NULS-USDT_bb100_2.5_sl3.0_ts1.7-0.3bep0.0493
