controller_name: xtreet_bb
controller_type: directional_trading
manual_kill_switch: null
candles_config: []
trading_pair: NULS-USDT
connector_name: binance_perpetual
interval: 1m
max_executors_per_side: 1
cooldown_time: 0
leverage: 20
position_mode: HEDGE
time_limit: 86400
dca_spreads:
- -1.0e-05
- 0.010898522644708171
dca_amounts_pct:
- 1
- 1.2529751279234582
bb_length: 50
bb_std: 1.5
stop_loss: 0.010898522644708171
take_profit: null
trailing_stop:
  activation_price: 0.010935601458080205
  trailing_delta: 0.002187120291616041
total_amount_quote: 300
candles_trading_pair: NULS-USDT
candles_connector: binance_perpetual
id: xtreet_bb_binance_perpetual_1m_NULS-USDT_bb50_1.5_sl1.1_ts1.1-0.2bep0.0061
