controller_name: xtreet_bb
controller_type: directional_trading
manual_kill_switch: null
candles_config: []
trading_pair: NULS-USDT
connector_name: binance_perpetual
interval: 1m
max_executors_per_side: 1
cooldown_time: 0
leverage: 20
position_mode: HEDGE
time_limit: 86400
dca_spreads:
- -1.0e-05
- 0.02632161026321615
dca_amounts_pct:
- 1
- 1.436562695911709
bb_length: 50
bb_std: 2.0
stop_loss: 0.011055956678700272
take_profit: null
trailing_stop:
  activation_price: 0.008857204579822961
  trailing_delta: 0.0017714409159645924
total_amount_quote: 300
candles_trading_pair: NULS-USDT
candles_connector: binance_perpetual
id: xtreet_bb_binance_perpetual_1m_NULS-USDT_bb50_2.0_sl1.1_ts0.9-0.2bep0.0155
