controller_name: xtreet_bb
controller_type: directional_trading
manual_kill_switch: null
candles_config: []
trading_pair: NULS-USDT
connector_name: binance_perpetual
interval: 1m
max_executors_per_side: 1
cooldown_time: 0
leverage: 20
position_mode: HEDGE
time_limit: 86400
dca_spreads:
- -1.0e-05
- 0.06325239746990405
dca_amounts_pct:
- 1
- 17.37398708501278
bb_length: 200
bb_std: 1.8
stop_loss: 0.033625730994152135
take_profit: null
trailing_stop:
  activation_price: 0.020758313916543168
  trailing_delta: 0.004151662783308634
total_amount_quote: 300
candles_trading_pair: NULS-USDT
candles_connector: binance_perpetual
id: xtreet_bb_binance_perpetual_1m_NULS-USDT_bb200_1.8_sl3.4_ts2.1-0.4bep0.0598
