controller_name: xtreet_bb
controller_type: directional_trading
manual_kill_switch: null
candles_config: []
trading_pair: NULS-USDT
connector_name: binance_perpetual
interval: 1m
max_executors_per_side: 1
cooldown_time: 0
leverage: 20
position_mode: HEDGE
time_limit: 86400
dca_spreads:
- -1.0e-05
- 0.01846901579586876
dca_amounts_pct:
- 1
- 1.4449972243649767
bb_length: 20
bb_std: 2.0
stop_loss: 0.008528784648187642
take_profit: null
trailing_stop:
  activation_price: 0.006512463507747617
  trailing_delta: 0.0013024927015495235
total_amount_quote: 300
candles_trading_pair: NULS-USDT
candles_connector: binance_perpetual
id: xtreet_bb_binance_perpetual_1m_NULS-USDT_bb20_2.0_sl0.9_ts0.7-0.1bep0.0109
