controller_name: xtreet_bb
controller_type: directional_trading
manual_kill_switch: null
candles_config: []
trading_pair: NULS-USDT
connector_name: binance_perpetual
interval: 1m
max_executors_per_side: 1
cooldown_time: 0
leverage: 20
position_mode: HEDGE
time_limit: 86400
dca_spreads:
- -1.0e-05
- 0.023845701692423164
dca_amounts_pct:
- 1
- 2.971032359925564
bb_length: 20
bb_std: 2.5
stop_loss: 0.010876256925918381
take_profit: null
trailing_stop:
  activation_price: 0.009694870874583525
  trailing_delta: 0.001938974174916705
total_amount_quote: 300
candles_trading_pair: NULS-USDT
candles_connector: binance_perpetual
id: xtreet_bb_binance_perpetual_1m_NULS-USDT_bb20_2.5_sl1.1_ts1.0-0.2bep0.0178
