controller_name: xtreet_bb
controller_type: directional_trading
manual_kill_switch: null
candles_config: []
trading_pair: NULS-USDT
connector_name: binance_perpetual
interval: 1m
max_executors_per_side: 1
cooldown_time: 0
leverage: 20
position_mode: HEDGE
time_limit: 86400
dca_spreads:
- -1.0e-05
- 0.020375680961707637
dca_amounts_pct:
- 1
- 5.453714554679414
bb_length: 50
bb_std: 1.4
stop_loss: 0.010714981492304813
take_profit: null
trailing_stop:
  activation_price: 0.007210950867758513
  trailing_delta: 0.0014421901735517028
total_amount_quote: 300
candles_trading_pair: NULS-USDT
candles_connector: binance_perpetual
id: xtreet_bb_binance_perpetual_1m_NULS-USDT_bb50_1.4_sl1.1_ts0.7-0.1bep0.0172
