controller_name: xtreet_bb
controller_type: directional_trading
manual_kill_switch: null
candles_config: []
trading_pair: NULS-USDT
connector_name: binance_perpetual
interval: 1m
max_executors_per_side: 1
cooldown_time: 0
leverage: 20
position_mode: HEDGE
time_limit: 86400
dca_spreads:
- -1.0e-05
- 0.05159635672032005
dca_amounts_pct:
- 1
- 1.4279287130361382
bb_length: 200
bb_std: 3.0
stop_loss: 0.04046242774566473
take_profit: null
trailing_stop:
  activation_price: 0.024102095832249606
  trailing_delta: 0.004820419166449922
total_amount_quote: 300
candles_trading_pair: NULS-USDT
candles_connector: binance_perpetual
id: xtreet_bb_binance_perpetual_1m_NULS-USDT_bb200_3.0_sl4.0_ts2.4-0.5bep0.0303
