controller_name: xtreet_bb
controller_type: directional_trading
manual_kill_switch: null
candles_config: []
trading_pair: NULS-USDT
connector_name: binance_perpetual
interval: 1m
max_executors_per_side: 1
cooldown_time: 0
leverage: 20
position_mode: HEDGE
time_limit: 86400
dca_spreads:
- -1.0e-05
- 0.010786248372330344
dca_amounts_pct:
- 1
- 1.341291079500888
bb_length: 100
bb_std: 1.5
stop_loss: 0.010786248372330344
take_profit: null
trailing_stop:
  activation_price: 0.013624796659316186
  trailing_delta: 0.0027249593318632373
total_amount_quote: 300
candles_trading_pair: NULS-USDT
candles_connector: binance_perpetual
id: xtreet_bb_binance_perpetual_1m_NULS-USDT_bb100_1.5_sl1.1_ts1.4-0.3bep0.0062
